version: '3'
services:
  database:
    container_name: 'PostgresDB'
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
  api:
    container_name: 'RentAppApi'
    image: docker.io/library/rent-app-java:0.0.1-SNAPSHOT
    ports:
      - '6060:6060'
    depends_on:
      - database
    restart: always
volumes:
  postgres-data:
    driver: local